###########################################################################################################
# Ansible Demonstration - Install packages
###########################################################################################################

---
# Install packages using system package manager

- name: Install cowsay
  hosts: all
  tasks:

    - name: Install cowsay package
      apt: 
        name: cowsay
        state: present
        update_cache: yes

    - name: Send a message with cowsay
      command: /usr/games/cowsay " The installation worked! "
