###########################################################################################################
# Ansible Demonstration - Create directory
###########################################################################################################

---
# Perform common system configuration tasks

- name: create_directory
  hosts: all
  tasks:

   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory